name: Interference NDK (windows)

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          submodules: 'recursive'

    - name: Add MinGW to PATH
      # Adds the UCRT64 MinGW environment to the system PATH
      run: |
        echo "C:\msys64\ucrt64\bin;C:\msys64\usr\bin;" | Out-File -FilePath $env:GITHUB_PATH -Encoding Utf8 -Append
      shell: powershell

    - name: Verify MinGW GCC installation
      run: gcc --version
      shell: bash

    - name: Configure CMake with MinGW Makefiles generator
      run: cmake -B build -G "MinGW Makefiles"
      # Alternatively, use the Ninja generator if installed:
      # run: cmake -B build -G Ninja
      shell: bash

    - name: Build project
      run: cmake --build build
      shell: bash
